# Generated by Django 5.2.5 on 2025-08-22 20:45

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=4),
        ),
    ]
