# Generated by Django 5.2.5 on 2025-08-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
