# Generated by Django 5.2.5 on 2025-09-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_country'),
        ('properties', '0002_alter_property_cover_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='timeline',
        ),
        migrations.AddField(
            model_name='lead',
            name='remote_purchase',
            field=models.BooleanField(blank=True, help_text='Whether the customer wants to complete the purchase remotely.', null=True, verbose_name='Buy remotely?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='visit_date',
            field=models.DateField(blank=True, help_text='If not remote, the date the customer plans to visit Cyprus.', null=True, verbose_name='Planned visit date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget (max)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget (min)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consent'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
    ]
