# Generated by Django 5.2.5 on 2025-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_options_remove_lead_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
    ]
